# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-12 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20141106_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actusensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('topic', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actusensor', to='tracker.User')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('command', models.CharField(max_length=50)),
                ('actusensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='tracker.Actusensor')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=50)),
                ('actusensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='tracker.Actusensor')),
            ],
        ),
        migrations.RemoveField(
            model_name='events',
            name='author',
        ),
        migrations.RemoveField(
            model_name='events',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='events',
            name='recurent',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Icon',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
